clear all
close all
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/dan/Library/CloudStorage/GoogleDrive-danleeharris@gmail.com/My Drive/1. Research/offshore_waves/CAWCR/May2022_storm.csv
%
% Auto-generated by MATLAB on 18-May-2023 14:25:32

%% Set up the Import Options and import the data


fstart = 'HCtimeseries_aus_4m_153.62E_28.04S_SC_2025_2026';
fend='.nc';
fname=[fstart fend];
Hs=nc_varget(fname,'hs');
Tp=nc_varget(fname,'t0m1');
Dir=nc_varget(fname,'dp');
Time=nc_varget(fname,'time');

%% Convert



date=datenum(1990,1,1)+Time;

dir_spread=repmat(30,length(date),1);

t = datetime(datevec(date));


X = convertTo(t,'yyyymmdd');
%change the start time if needed
hrs_M=[0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23];
hrs_M=hrs_M';

hrs=repmat(hrs_M,round(length(Dir)/24),1);

final_time=X+hrs(1:length(X));

M=[final_time Hs Tp Dir dir_spread];

dlmwrite([fstart '.tpar'],M,'delimiter',' ','precision','%.6f')


%save("wave_offshore_1982_1990.mat","date","Hs","Tp","Dir");